SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ─────────────────────────────────────────────────────────────────────────────
-- SCHEMAS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE SCHEMA auth;
CREATE SCHEMA clinic;

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLES (auth)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE auth.clinic_role (
    id bigint NOT NULL,
    code character varying(3) NOT NULL,
    display_name character varying(50) NOT NULL
);

ALTER TABLE auth.clinic_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.clinic_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.clinic_user (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(150) NOT NULL,
    phone_number character varying(9) NOT NULL,
    account_non_locked boolean NOT NULL,
    enabled boolean NOT NULL,
    login_attempts integer,
    recuperation_token character varying(6),
    recuperation_token_exp_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE auth.clinic_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.clinic_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.clinic_role_user (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE auth.clinic_role_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.clinic_role_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.refresh_token (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    fingerprint character varying(64) NOT NULL,
    token_hash character varying(100) NOT NULL,
    is_revoked boolean NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE auth.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLES (clinic)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE clinic.schedules (
    id bigint NOT NULL,
    clinic_id bigint NOT NULL,
    week_day VARCHAR(10) NOT NULL,
    opening TIME NOT NULL,
    closing TIME NOT NULL,
    closed boolean NOT NULL
);

ALTER TABLE clinic.schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clinic.schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE clinic.clinic (
    id bigint NOT NULL,
    clinic_name VARCHAR(200) NOT NULL,
    address VARCHAR(350) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE clinic.clinic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clinic.clinic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONSTRAINTS (PK & UNIQUE)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE ONLY auth.clinic_role
    ADD CONSTRAINT role_code_unique UNIQUE (code);

ALTER TABLE ONLY auth.clinic_role
    ADD CONSTRAINT role_displayName_unique UNIQUE (display_name);

ALTER TABLE ONLY auth.clinic_role
    ADD CONSTRAINT clinic_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.clinic_user
    ADD CONSTRAINT user_username_unique UNIQUE (username);

ALTER TABLE ONLY auth.clinic_user
    ADD CONSTRAINT clinic_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.clinic_role_user
    ADD CONSTRAINT role_user_roleId_userId_unique UNIQUE (role_id, user_id);

ALTER TABLE ONLY auth.clinic_role_user
    ADD CONSTRAINT clinic_role_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.refresh_token
    ADD CONSTRAINT refresh_token_fingerprint_unique UNIQUE (fingerprint);

ALTER TABLE ONLY auth.refresh_token
    ADD CONSTRAINT refresh_token_token_hash_unique UNIQUE (token_hash);

ALTER TABLE ONLY auth.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clinic.schedules
    ADD CONSTRAINT schedules_clinic_id_day_unique UNIQUE (clinic_id,week_day);

ALTER TABLE ONLY clinic.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clinic.clinic
    ADD CONSTRAINT clinic_clinic_name_unique UNIQUE (clinic_name);

ALTER TABLE ONLY clinic.clinic
    ADD CONSTRAINT clinic_pkey PRIMARY KEY (id);

-- ─────────────────────────────────────────────────────────────────────────────
-- ÍNDICES (BTREE)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX fk_clinic_role_user_clinic_role_idx ON auth.clinic_role_user USING btree (role_id);
CREATE INDEX fk_clinic_role_user_clinic_user_idx ON auth.clinic_role_user USING btree (user_id);
CREATE INDEX fk_refresh_token_clinic_user_idx ON auth.refresh_token USING btree (user_id);
CREATE INDEX fk_schedules_clinic_idx ON clinic.schedules USING btree (clinic_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- FOREIGN KEYS
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE ONLY auth.clinic_role_user
    ADD CONSTRAINT fk_clinic_role_user_clinic_role FOREIGN KEY (role_id)
    REFERENCES auth.clinic_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.clinic_role_user
    ADD CONSTRAINT fk_clinic_role_user_clinic_user FOREIGN KEY (user_id)
    REFERENCES auth.clinic_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.refresh_token
    ADD CONSTRAINT fk_refresh_token_clinic_user FOREIGN KEY (user_id)
    REFERENCES auth.clinic_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY clinic.schedules
    ADD CONSTRAINT fk_schedules_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinic.clinic(id);